@startuml
Trigger --> AccountTriggerHandler
TriggerHandler <|-- AccountTriggerHandler : Extends
AccountTriggerHandler --> AccountServiceLayer : Calls

TriggerHandler : run()
TriggerHandler : beforeInsert() : stub
TriggerHandler : afterUpdate() : stub

AccountTriggerHandler : beforeInsert()
AccountTriggerHandler : afterUpdate()

AccountServiceLayer : changeShippingStreet()
AccountServiceLayer : justWriteALogStatement()
AccountServiceLayer : incrementCounterInDescription()

@enduml